### ISSUE TITLE
Options not loaded at launch

### ISSUE THREAD

**Issue by malexandre** [braver/isotope-ui#14] opened 2015-01-28 22:16 UTC
Everytime I launch Atom, I have to change theme and re-change back to Isotope to get back my background image, the decorated gutter, and even the Isotope way of displaying the non-commited file.
The settings are still available, but just not applied.

At launch:
![](http://i.imgur.com/OzieMlB.png)

After theme change:
![](http://i.imgur.com/8UmUwnF.png)

Atom version: 0.176.0
Isotope version: 1.2.8

**Comment by Nxt3** [comment] 2015-01-29 17:11
Same here. Same version of Isotope and Atom. (I'm on Linux)

I feel like this may not be an Isotope issue, and more of an Atom issue. On Atom v0.175.0, Isotope was working admirably.

**Comment by braver** [comment] 2015-01-29 18:49
It's weird, I'm unable to reproduce this when testing on Ubuntu 1410, Atom 0.176.0, Isotope 1.2.8. There are some known issues that may be related, like https://github.com/atom/settings-view/issues/347... In a way I'm like "let's see what 0.177 brings"...? Not sure there's anything I can do at this point.

**Comment by braver** [comment] 2015-02-11 07:40
@malexandre @Nxt3 Guys, are you still getting this?

**Comment by malexandre** [comment] 2015-02-11 08:50
@braver I can't install the last Atom release (0.178.0) because it's broke on my Fedora. But it's working. There is one probleme though: The gutter is not styled by Isotope anymore, I don't know why.

**Comment by braver** [comment] 2015-02-11 09:32
Yes, that's right. I had some feedback on the gutter style, reconsidered, and feel that that's really in the domain of the syntax theme and I shouldn't mess with it. I took out the option because I really needed to reel in the configurability to keep it maintainable.

I'm closing this for now. If anything crops up again let me know.

**Closed as completed by braver** 2015-02-11 09:32 UTC
